:concurrency: 4
staging:
  :concurrency: 4
production:
  :concurrency: 4
:logfile: ./log/sidekiq.log
:queues:
  - priority
  - mailers
  - brick_owl
  - ebay
  - bricklink
  - default
:limits:
  brick_owl: 1
